DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS logins CASCADE;

CREATE TABLE users (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(100),
	email TEXT UNIQUE NOT NULL,
	entries BIGINT DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT Now()
);

CREATE TABLE logins (
	id SERIAL PRIMARY KEY NOT NULL,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	hash VARCHAR(100)
);